//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CibleWebForms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CibleRhWebAppEntities : DbContext
    {
        public CibleRhWebAppEntities()
            : base("name=CibleRhWebAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avance> Avances { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Societe> Societes { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
